### PR TITLE
Add bitcode support

### PR DESCRIPTION
**Pull request by tomassliz**
Add `opencore-amr` binaries with bitcode support and update podspec to version `0.1.2`.

### CODE REVIEW

**Comment by lanceylai** [comment]
Thanks for you PR

**Comment by tomassliz** [comment]
You're welcome. When will be the new pod version available please? Maybe you have to add new version tag to this repository?

**Comment by lanceylai** [comment]
I will update it and check the PR validation later. 👍

**Comment by tomassliz** [comment]
Sorry, I don't understand. Your version of pod is 0.39.0? Because when I look on tags in this repo, I see latest version is 0.1.1 and this pull request updated podspec to version 0.1.2. And I still can't use this last pod in version 0.1.2. So what is needed now?

**Comment by lanceylai** [comment]
I've been update the tag to 0.1.2. Have a try?

**Comment by tomassliz** [comment]
Nice, thank you! 👍

**Pull request merged**
