### PR TITLE
Add swift 4 support

### PR DESCRIPTION
**Pull request by libec**

### CODE REVIEW

**Comment by libec** [comment]
Hey @hilen could you take a look and tell me if that's all there is for the swift 4 conversion? We're gonna have to release after that.

**Comment by lanceylai** [comment]
Thanks for the PR, I've been updated it.

**Comment by libec** [comment]
Can we also prep the new release so that it's installable via pods?

**Comment by lanceylai** [comment]
🎉  Congrats

 🚀  TSVoiceConverter (0.1.6) successfully published
 📅  October 26th, 09:21
 🌎  https://cocoapods.org/pods/TSVoiceConverter
 👍  Tell your friends!

Have a try.

**Comment by libec** [comment]
Thanks. You rock! 🎉

**Pull request merged**
